spring:
  security:
    oauth2:
      client:
        registration:
          #GOOGLE oauth2 setting
        google:
          client-id: 308271916937-8mabtmnv1nabh9tsuvtiruen69r6390m.apps.googleusercontent.com
          client-secret: gUYJvqXSJ0vem5Kf0tEV1xMZ
          scope:
            - profile
            - email

        naver:
          client-id:
          client-secret:
          redirect_uri_template: localhost:8085/{action}/oauth2/code/{registrationId}
          authorization_grant_type: authorization_code
          scope:
            - name
            - emaiL
            - profile_image
          client-name: Naver

          # provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response