server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ggomiluv?characterEncoding=utf8
    username: ggomi
    password: ggomi1234!
    driver-class-name: com.mysql.cj.jdbc.Driver


  messages:
    basename: message/message

  thymeleaf:
    cache: false
#  profiles:
#    include: oauth

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
